name = "WeightedCVT"
uuid = "770ca0ce-b1ea-490c-93de-6aee52022c72"
authors = ["Mikhail Khrenov <mkhrenov34@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
